name: Build Kernel
on:
  workflow_dispatch:
    inputs:
      BRANCH:
        description: Kernel branch
        default: 'master'
        required: true
      URL:
        description: Repository URL
        default: 'https://github.com/rsuntkOrgs/android_kernel_samsung_a05m-6.6.git'
        required: true
      KSU:
        description: Add KernelSU support
        type: boolean
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        path: rootdir
        show-progress: false
        fetch-depth: 1
        
    - name: Prepare dependencies
      run: |
        sudo apt update -y
        sudo apt install rsync bc cpio flex bison aptitude aria2 git python-is-python3 tar perl wget curl lz4 -y
        sudo aptitude install libssl-dev -y
        
    - name: Clone Kernel Source
      run: git clone --depth=1 --single-branch -b ${{ inputs.BRANCH }} ${{ inputs.URL }} kernel_root

    - name: Fetch toolchains
      run: |
        aria2c https://github.com/rsuntkOrgs/android_kernel_samsung_a05m-6.6/releases/download/v1.0/xaa
        aria2c https://github.com/rsuntkOrgs/android_kernel_samsung_a05m-6.6/releases/download/v1.0/xab
        echo "INFO: Appending files and extracting ..."
        cat xaa xab > toolchains.tar.gz && tar -xf toolchains.tar.gz && rm toolchains.tar.gz xaa xab
        [ ! -f $(pwd)/xaa ] && echo "INFO: Extraction operation is completed." || exit 1
      working-directory: kernel_root

    - name: Prepare timezone fix
      run: |
        sudo rm /etc/localtime
        sudo ln -s /usr/share/zoneinfo/Asia/Jakarta /etc/localtime

    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: 21

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    
    - name: Build kernel
      id: buildKernel
      continue-on-error: true
      run: |
        if [ "${{ inputs.KSU }}" == "true" ]; then
          cd kernel-6.6 && curl -LSs "https://raw.githubusercontent.com/rsuntk/KernelSU/main/kernel/setup.sh" | bash -s main && cd ..
        fi
        kernelVersion=$(cd kernel-6.6 && make kernelversion && cd ..)
        [ -f $(pwd)/build_kernel.sh ] && bash build_kernel.sh || exit 1
        cd out && find . -type f -name "Image.gz" && cd ..
        gitsha1=$(git rev-parse --short HEAD)
        buildDetails="$kernelVersion-A055X_`echo $gitsha1`-`date +'%Y%m%d%H%M%S'`" && echo "buildDetails=$buildDetails" >> $GITHUB_OUTPUT
      working-directory: kernel_root
